repos:
  - repo: local
    hooks:
      - id: lint-charts
        name: Lint charts
        language: docker_image
        always_run: true
        pass_filenames: false
        entry: quay.io/helmpack/chart-testing ct lint --config test/ct.yaml
      - id: package-charts
        name: Package charts
        language: system
        always_run: true
        pass_filenames: false
        entry: bash test/package-charts.sh

